### ISSUE TITLE
How to regist?

### ISSUE THREAD

**Issue by r90** [piccagliani/redmine_nikoniko_calendar2#4]
HI, Its't very nice and cool plugin!
But I don't know how to use this. Where is regist button or calendar?
My "ニコニコカレンダー" page has only "ニコニコ履歴" letter.

**Comment by piccagliani** [comment]
@r90 

Thank you for trying this plugin!

> My "ニコニコカレンダー" page has only "ニコニコ履歴" letter.

Hmm, that's strange.....

I expect that screen like [screenshots](https://github.com/piccagliani/redmine_nikoniko_calendar2/wiki) is displayed.

Did you have javascript errors?

**Comment by r90** [comment]
It's solved.It seems setting mistake, sorry.
This calendar very cool! Thanks! :)

**Comment by piccagliani** [comment]
Ok, no problems. :)
